### ISSUE TITLE
ngscrape wants the self tag when scraping a game [BUG]

### ISSUE THREAD

**Issue by shadow9owo** [aeiea/ngscrape#1]
when i scrape a game w ngscrape it requires an self tag
which is not documented in the documentation on how to scrap games
and when i add something none or 0 or "" it says smthing along the lines of

AttributeError: x object has no attribute 'cache'

meaning that it always just errors out and dosent scrap anything game related

**Comment by aeiea** [comment]
oh! sorry, i patched it on my desktop PC but forgot to commit, and I'm traveling rn, so I cant commit it for now. ill try to fix it asap.

**Comment by aeiea** [comment]
oh wait nvm i misread, try using the raw file
remember to rename it to ngscrape.py, and move it into ur prjct folder
[ngscrape.txt](https://github.com/aeiea/ngscrape/files/12144082/ngscrape.txt)

**Comment by aeiea** [comment]
and if ur new to python just ignore the self arg, in modules its ignored as it contains instance data(stuff u should not touch)

**Comment by aeiea** [comment]
example:
```python
import ngscrape
sc = ngscrape.Scraper()
sc.scrape_game('https://www.newgrounds.com/portal/view/59593')
```

**Comment by shadow9owo** [comment]
gotcha thx
